### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
- *Repackage*

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
Uh... weird.

**Comment by ericgaspar** [comment]
I have tested multi-instances in my server (production, of course) and it works... NGINX gets the path with `__2` right.

**Comment by ericgaspar** [comment]
And the old CI does not report any errors.

**Pull request merged**
