### PR TITLE
Multi instance

### PR DESCRIPTION
**Pull request by OniriCorpe**
## Problem

- bookstack_ynh isn't a multi_instance package where there is nothing to restrict it

## Solution

- edit the configuration to enable multi_instance setting and testing

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

```
 ============================================
  [Test 5/10] Multi-instance installations
 ============================================


 > First installation: path=sub.domain.tld/

(Reusing existing snapshot snap_rootinstall)

 > Second installation: path=domain.tld/

Running: yunohost app install --force /app_folder -a "domain=domain.tld&path=/&admin=package_checker&password=1Strong-Password&language=fr&is_public=1&"
2110 INFO Installing bookstack...
3478 INFO [....................] > Validating installation parameters...
4599 INFO [....................] > Storing installation settings...
6200 INFO [....................] > Installing dependencies...
34277 INFO [....................] > Creating a MySQL database...
35180 INFO [+...................] > Configuring system user...
35776 INFO [#++.................] > Setting up source files...
37874 INFO [###.................] > Configuring NGINX web server...
40252 INFO [###+................] > Configuring PHP-FPM...
45328 INFO [####+...............] > Installing BookStack with Composer...
61046 INFO [#####...............] > Adding a configuration file...
63199 INFO [#####+..............] > Install BookStack
72903 INFO [######+++++++++++++.] > Configuring permissions...
74254 INFO [###################.] > Reloading NGINX web server...
74766 INFO [####################] > Installation of bookstack__2 completed
76826 SUCCESS Installation completed

 > Validating that the app bookstack can/can't be accessed with its URL...


 > Validating that the app bookstack__2 can/can't be accessed with its URL...


 > Removing the app...

421  INFO Removing bookstack...
873  INFO [+...................] > Loading installation settings...
1678 INFO [#++.................] > Removing the MySQL database...
2920 INFO [###++...............] > Removing the redis database...
3172 INFO [#####++++...........] > Removing app main directory...
4897 INFO [#########+..........] > Removing NGINX web server configuration...
5408 INFO [##########++++......] > Removing PHP-FPM configuration...
18409 INFO [##############++....] > Removing dependencies...
23451 WARNING E: Unable to locate package bookstack-ynh-deps
23608 INFO [################++..] > Removing the dedicated system user...
24239 INFO [####################] > Removal of bookstack completed
25248 SUCCESS bookstack uninstalled

 > Validating that the app bookstack__2 can/can't be accessed with its URL...


--- SUCCESS ---

Working time for this test: 3 minutes, 56 seconds (20:36:01)
```

### CODE REVIEW

**Comment by OniriCorpe** [comment]
!testme

**Comment by OniriCorpe** [comment]
Weird, `Install (private)` test passes in my VM running [package_check](https://github.com/YunoHost/package_check)

I re-run the tests on the CI

!testme

**Comment by OniriCorpe** [comment]
!testme

**Comment by ericgaspar** [comment]
> Weird, `Install (private)` test passes in my VM running [package_check](https://github.com/YunoHost/package_check)
> 
> I re-run the tests on the CI

this is a bug in the CI. Should be ok

**Pull request merged**
